// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.operationtemplates.models;

import com.azure.core.util.Context;

/**
 * Resource collection API of Lroes.
 */
public interface Lroes {
    /**
     * Delete a LroResource.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param lroResourceName The name of the LroResource.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    void deleteByResourceGroup(String resourceGroupName, String lroResourceName);

    /**
     * Delete a LroResource.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param lroResourceName The name of the LroResource.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    void delete(String resourceGroupName, String lroResourceName, Context context);

    /**
     * Delete a LroResource.
     * 
     * @param id the resource ID.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    void deleteById(String id);

    /**
     * Delete a LroResource.
     * 
     * @param id the resource ID.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    void deleteByIdWithResponse(String id, Context context);

    /**
     * Begins definition for a new LroResource resource.
     * 
     * @param name resource name.
     * @return the first stage of the new LroResource definition.
     */
    LroResource.DefinitionStages.Blank define(String name);
}
