// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.operationtemplates.fluent;

import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.management.polling.PollResult;
import com.azure.core.util.Context;
import com.azure.core.util.polling.SyncPoller;
import com.azure.resourcemanager.operationtemplates.fluent.models.LroResourceInner;

/**
 * An instance of this class provides access to all the operations defined in LroesClient.
 */
public interface LroesClient {
    /**
     * Create a LroResource.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param lroResourceName The name of the LroResource.
     * @param resource Resource create parameters.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the {@link SyncPoller} for polling of concrete tracked resource types can be created by aliasing this
     * type using a specific property type.
     */
    @ServiceMethod(returns = ReturnType.LONG_RUNNING_OPERATION)
    SyncPoller<PollResult<LroResourceInner>, LroResourceInner> beginCreateOrReplace(String resourceGroupName,
        String lroResourceName, LroResourceInner resource);

    /**
     * Create a LroResource.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param lroResourceName The name of the LroResource.
     * @param resource Resource create parameters.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the {@link SyncPoller} for polling of concrete tracked resource types can be created by aliasing this
     * type using a specific property type.
     */
    @ServiceMethod(returns = ReturnType.LONG_RUNNING_OPERATION)
    SyncPoller<PollResult<LroResourceInner>, LroResourceInner> beginCreateOrReplace(String resourceGroupName,
        String lroResourceName, LroResourceInner resource, Context context);

    /**
     * Create a LroResource.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param lroResourceName The name of the LroResource.
     * @param resource Resource create parameters.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return concrete tracked resource types can be created by aliasing this type using a specific property type.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    LroResourceInner createOrReplace(String resourceGroupName, String lroResourceName, LroResourceInner resource);

    /**
     * Create a LroResource.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param lroResourceName The name of the LroResource.
     * @param resource Resource create parameters.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return concrete tracked resource types can be created by aliasing this type using a specific property type.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    LroResourceInner createOrReplace(String resourceGroupName, String lroResourceName, LroResourceInner resource,
        Context context);

    /**
     * Delete a LroResource.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param lroResourceName The name of the LroResource.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the {@link SyncPoller} for polling of long-running operation.
     */
    @ServiceMethod(returns = ReturnType.LONG_RUNNING_OPERATION)
    SyncPoller<PollResult<Void>, Void> beginDelete(String resourceGroupName, String lroResourceName);

    /**
     * Delete a LroResource.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param lroResourceName The name of the LroResource.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the {@link SyncPoller} for polling of long-running operation.
     */
    @ServiceMethod(returns = ReturnType.LONG_RUNNING_OPERATION)
    SyncPoller<PollResult<Void>, Void> beginDelete(String resourceGroupName, String lroResourceName, Context context);

    /**
     * Delete a LroResource.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param lroResourceName The name of the LroResource.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    void delete(String resourceGroupName, String lroResourceName);

    /**
     * Delete a LroResource.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param lroResourceName The name of the LroResource.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    void delete(String resourceGroupName, String lroResourceName, Context context);
}
