// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.operationtemplates.implementation;

import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.operationtemplates.fluent.LroesClient;
import com.azure.resourcemanager.operationtemplates.models.Lroes;

public final class LroesImpl implements Lroes {
    private static final ClientLogger LOGGER = new ClientLogger(LroesImpl.class);

    private final LroesClient innerClient;

    private final com.azure.resourcemanager.operationtemplates.OperationTemplatesManager serviceManager;

    public LroesImpl(LroesClient innerClient,
        com.azure.resourcemanager.operationtemplates.OperationTemplatesManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public void deleteByResourceGroup(String resourceGroupName, String lroResourceName) {
        this.serviceClient().delete(resourceGroupName, lroResourceName);
    }

    public void delete(String resourceGroupName, String lroResourceName, Context context) {
        this.serviceClient().delete(resourceGroupName, lroResourceName, context);
    }

    public void deleteById(String id) {
        String resourceGroupName = ResourceManagerUtils.getValueFromIdByName(id, "resourceGroups");
        if (resourceGroupName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'resourceGroups'.", id)));
        }
        String lroResourceName = ResourceManagerUtils.getValueFromIdByName(id, "lroResources");
        if (lroResourceName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'lroResources'.", id)));
        }
        this.delete(resourceGroupName, lroResourceName, Context.NONE);
    }

    public void deleteByIdWithResponse(String id, Context context) {
        String resourceGroupName = ResourceManagerUtils.getValueFromIdByName(id, "resourceGroups");
        if (resourceGroupName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'resourceGroups'.", id)));
        }
        String lroResourceName = ResourceManagerUtils.getValueFromIdByName(id, "lroResources");
        if (lroResourceName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'lroResources'.", id)));
        }
        this.delete(resourceGroupName, lroResourceName, context);
    }

    private LroesClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.resourcemanager.operationtemplates.OperationTemplatesManager manager() {
        return this.serviceManager;
    }

    public LroResourceImpl define(String name) {
        return new LroResourceImpl(name, this.manager());
    }
}
