// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.operationtemplates.implementation;

import com.azure.core.management.Region;
import com.azure.core.management.SystemData;
import com.azure.core.util.Context;
import com.azure.resourcemanager.operationtemplates.fluent.models.LroResourceInner;
import com.azure.resourcemanager.operationtemplates.models.LroResource;
import com.azure.resourcemanager.operationtemplates.models.LroResourceProperties;
import java.util.Collections;
import java.util.Map;

public final class LroResourceImpl implements LroResource, LroResource.Definition {
    private LroResourceInner innerObject;

    private final com.azure.resourcemanager.operationtemplates.OperationTemplatesManager serviceManager;

    LroResourceImpl(LroResourceInner innerObject,
        com.azure.resourcemanager.operationtemplates.OperationTemplatesManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String location() {
        return this.innerModel().location();
    }

    public Map<String, String> tags() {
        Map<String, String> inner = this.innerModel().tags();
        if (inner != null) {
            return Collections.unmodifiableMap(inner);
        } else {
            return Collections.emptyMap();
        }
    }

    public LroResourceProperties properties() {
        return this.innerModel().properties();
    }

    public SystemData systemData() {
        return this.innerModel().systemData();
    }

    public Region region() {
        return Region.fromName(this.regionName());
    }

    public String regionName() {
        return this.location();
    }

    public LroResourceInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.operationtemplates.OperationTemplatesManager manager() {
        return this.serviceManager;
    }

    private String resourceGroupName;

    private String lroResourceName;

    public LroResourceImpl withExistingResourceGroup(String resourceGroupName) {
        this.resourceGroupName = resourceGroupName;
        return this;
    }

    public LroResource create() {
        this.innerObject = serviceManager.serviceClient()
            .getLroes()
            .createOrReplace(resourceGroupName, lroResourceName, this.innerModel(), Context.NONE);
        return this;
    }

    public LroResource create(Context context) {
        this.innerObject = serviceManager.serviceClient()
            .getLroes()
            .createOrReplace(resourceGroupName, lroResourceName, this.innerModel(), context);
        return this;
    }

    LroResourceImpl(String name,
        com.azure.resourcemanager.operationtemplates.OperationTemplatesManager serviceManager) {
        this.innerObject = new LroResourceInner();
        this.serviceManager = serviceManager;
        this.lroResourceName = name;
    }

    public LroResourceImpl withRegion(Region location) {
        this.innerModel().withLocation(location.toString());
        return this;
    }

    public LroResourceImpl withRegion(String location) {
        this.innerModel().withLocation(location);
        return this;
    }

    public LroResourceImpl withTags(Map<String, String> tags) {
        this.innerModel().withTags(tags);
        return this;
    }

    public LroResourceImpl withProperties(LroResourceProperties properties) {
        this.innerModel().withProperties(properties);
        return this;
    }
}
