// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * Package containing the implementations for OperationTemplates.
 * Arm Resource Provider management API.
 */
package com.azure.resourcemanager.operationtemplates.implementation;
