// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package tsptest.armstreamstyleserialization.implementation;

import com.azure.v2.core.management.AzureEnvironment;
import io.clientcore.core.annotations.ServiceClientBuilder;
import io.clientcore.core.http.pipeline.HttpPipeline;
import io.clientcore.core.http.pipeline.HttpPipelineBuilder;
import java.time.Duration;

/**
 * A builder for creating a new instance of the ArmStreamStyleSerializationClientImpl type.
 */
@ServiceClientBuilder(serviceClients = { ArmStreamStyleSerializationClientImpl.class })
public final class ArmStreamStyleSerializationClientBuilder {
    /*
     * Service host
     */
    private String endpoint;

    /**
     * Sets Service host.
     * 
     * @param endpoint the endpoint value.
     * @return the ArmStreamStyleSerializationClientBuilder.
     */
    public ArmStreamStyleSerializationClientBuilder endpoint(String endpoint) {
        this.endpoint = endpoint;
        return this;
    }

    /*
     * The ID of the target subscription. The value must be an UUID.
     */
    private String subscriptionId;

    /**
     * Sets The ID of the target subscription. The value must be an UUID.
     * 
     * @param subscriptionId the subscriptionId value.
     * @return the ArmStreamStyleSerializationClientBuilder.
     */
    public ArmStreamStyleSerializationClientBuilder subscriptionId(String subscriptionId) {
        this.subscriptionId = subscriptionId;
        return this;
    }

    /*
     * The environment to connect to
     */
    private AzureEnvironment environment;

    /**
     * Sets The environment to connect to.
     * 
     * @param environment the environment value.
     * @return the ArmStreamStyleSerializationClientBuilder.
     */
    public ArmStreamStyleSerializationClientBuilder environment(AzureEnvironment environment) {
        this.environment = environment;
        return this;
    }

    /*
     * The HTTP pipeline to send requests through
     */
    private HttpPipeline pipeline;

    /**
     * Sets The HTTP pipeline to send requests through.
     * 
     * @param pipeline the pipeline value.
     * @return the ArmStreamStyleSerializationClientBuilder.
     */
    public ArmStreamStyleSerializationClientBuilder pipeline(HttpPipeline pipeline) {
        this.pipeline = pipeline;
        return this;
    }

    /*
     * The default poll interval for long-running operation
     */
    private Duration defaultPollInterval;

    /**
     * Sets The default poll interval for long-running operation.
     * 
     * @param defaultPollInterval the defaultPollInterval value.
     * @return the ArmStreamStyleSerializationClientBuilder.
     */
    public ArmStreamStyleSerializationClientBuilder defaultPollInterval(Duration defaultPollInterval) {
        this.defaultPollInterval = defaultPollInterval;
        return this;
    }

    /**
     * Builds an instance of ArmStreamStyleSerializationClientImpl with the provided parameters.
     * 
     * @return an instance of ArmStreamStyleSerializationClientImpl.
     */
    public ArmStreamStyleSerializationClientImpl buildClient() {
        String localEndpoint = (endpoint != null) ? endpoint : "https://management.azure.com";
        AzureEnvironment localEnvironment = (environment != null) ? environment : AzureEnvironment.AZURE;
        HttpPipeline localPipeline = (pipeline != null)
            ? pipeline
            : new HttpPipelineBuilder().policies(new UserAgentPolicy(), new RetryPolicy()).build();
        Duration localDefaultPollInterval
            = (defaultPollInterval != null) ? defaultPollInterval : Duration.ofSeconds(30);
        ArmStreamStyleSerializationClientImpl client
            = new ArmStreamStyleSerializationClientImpl(localPipeline, localEndpoint, this.subscriptionId);
        return client;
    }
}
