// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package tsptest.armstreamstyleserialization.implementation;

import com.azure.v2.core.util.FluxUtil;
import io.clientcore.core.annotations.Headers;
import io.clientcore.core.annotations.ReturnType;
import io.clientcore.core.annotations.ServiceInterface;
import io.clientcore.core.annotations.ServiceMethod;
import io.clientcore.core.http.RestProxy;
import io.clientcore.core.http.annotations.BodyParam;
import io.clientcore.core.http.annotations.HeaderParam;
import io.clientcore.core.http.annotations.HostParam;
import io.clientcore.core.http.annotations.HttpRequestInformation;
import io.clientcore.core.http.annotations.UnexpectedResponseExceptionDetail;
import io.clientcore.core.http.exceptions.HttpResponseException;
import io.clientcore.core.http.models.HttpMethod;
import io.clientcore.core.http.models.Response;
import io.clientcore.core.http.pipeline.HttpPipeline;
import io.clientcore.core.serialization.ObjectSerializer;
import io.clientcore.core.utils.Context;
import java.lang.reflect.InvocationTargetException;
import reactor.core.publisher.Mono;
import tsptest.armstreamstyleserialization.fluent.FishesClient;
import tsptest.armstreamstyleserialization.fluent.models.FishInner;
import tsptest.armstreamstyleserialization.fluent.models.OutputOnlyModelInner;
import tsptest.armstreamstyleserialization.models.Error;
import tsptest.armstreamstyleserialization.models.ErrorMin;

/**
 * An instance of this class provides access to all the operations defined in FishesClient.
 */
public final class FishesClientImpl implements FishesClient {
    /**
     * The proxy service used to perform REST calls.
     */
    private final FishesService service;

    /**
     * The service client containing this operation class.
     */
    private final ArmStreamStyleSerializationClientImpl client;

    /**
     * Initializes an instance of FishesClientImpl.
     * 
     * @param client the instance of the service client containing this operation class.
     */
    FishesClientImpl(ArmStreamStyleSerializationClientImpl client) {
        this.service = RestProxy.create(FishesService.class, client.getHttpPipeline());
        this.client = client;
    }

    /**
     * The interface defining all the services for ArmStreamStyleSerializationClientFishes to be used by the proxy
     * service to perform REST calls.
     */
    @ServiceInterface(name = "ArmStreamStyleSerial", host = "{endpoint}")
    public interface FishesService {
        static FishesService getNewInstance(HttpPipeline pipeline, ObjectSerializer serializer) {
            try {
                Class<?> clazz = Class.forName("tsptest.armstreamstyleserialization.implementation.FishesServiceImpl");
                return (FishesService) clazz.getMethod("getNewInstance", HttpPipeline.class, ObjectSerializer.class)
                    .invoke(null, pipeline, serializer);
            } catch (ClassNotFoundException | NoSuchMethodException | IllegalAccessException
                | InvocationTargetException e) {
                throw new RuntimeException(e);
            }

        }

        @Headers({ "Content-Type: application/json" })
        @HttpRequestInformation(method = HttpMethod.GET, path = "/model", expectedStatusCodes = { 200 })
        @UnexpectedResponseExceptionDetail(exceptionBodyClass = Error.class)
        Mono<Response<FishInner>> getModel(@HostParam("endpoint") String endpoint,
            @HeaderParam("Accept") String accept);

        @HttpRequestInformation(method = HttpMethod.PUT, path = "/model", expectedStatusCodes = { 200 })
        @UnexpectedResponseExceptionDetail(exceptionBodyClass = ErrorMin.class)
        Mono<Response<FishInner>> putModel(@HostParam("endpoint") String endpoint,
            @HeaderParam("Content-Type") String contentType, @HeaderParam("Accept") String accept,
            @BodyParam("application/json") FishInner fish);

        @Headers({ "Content-Type: application/json" })
        @HttpRequestInformation(method = HttpMethod.GET, path = "/model/output", expectedStatusCodes = { 200 })
        @UnexpectedResponseExceptionDetail
        Mono<Response<OutputOnlyModelInner>> getOutputOnlyModel(@HostParam("endpoint") String endpoint,
            @HeaderParam("Accept") String accept);
    }

    /**
     * The getModel operation.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic multiple levels inheritance with a discriminator on successful
     * completion of {@link Mono}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private Mono<Response<FishInner>> getModelWithResponseAsync() {
        if (this.client.getEndpoint() == null) {
            return Mono.error(
                new IllegalArgumentException("Parameter this.client.getEndpoint() is required and cannot be null."));
        }
        final String accept = "application/json";
        return FluxUtil.withContext(context -> service.getModel(this.client.getEndpoint(), accept))
            .contextWrite(context -> context.putAll(FluxUtil.toReactorContext(this.client.getContext()).readOnly()));
    }

    /**
     * The getModel operation.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic multiple levels inheritance with a discriminator on successful
     * completion of {@link Mono}.
     */
    private Mono<FishInner> getModelAsync() {
        return getModelWithResponseAsync().flatMap(res -> Mono.justOrEmpty(res.getValue()));
    }

    /**
     * The getModel operation.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic multiple levels inheritance with a discriminator.
     */
    public Response<FishInner> getModelWithResponse() {
        return getModelWithResponseAsync().block();
    }

    /**
     * The getModel operation.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic multiple levels inheritance with a discriminator.
     */
    public FishInner getModel() {
        return getModelWithResponse(Context.none()).getValue();
    }

    /**
     * The putModel operation.
     * 
     * @param fish The fish parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic multiple levels inheritance with a discriminator on successful
     * completion of {@link Mono}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private Mono<Response<FishInner>> putModelWithResponseAsync(FishInner fish) {
        if (this.client.getEndpoint() == null) {
            return Mono.error(
                new IllegalArgumentException("Parameter this.client.getEndpoint() is required and cannot be null."));
        }
        if (fish == null) {
            return Mono.error(new IllegalArgumentException("Parameter fish is required and cannot be null."));
        } else {
            fish.validate();
        }
        final String contentType = "application/json";
        final String accept = "application/json";
        return FluxUtil.withContext(context -> service.putModel(this.client.getEndpoint(), contentType, accept, fish))
            .contextWrite(context -> context.putAll(FluxUtil.toReactorContext(this.client.getContext()).readOnly()));
    }

    /**
     * The putModel operation.
     * 
     * @param fish The fish parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic multiple levels inheritance with a discriminator on successful
     * completion of {@link Mono}.
     */
    private Mono<FishInner> putModelAsync(FishInner fish) {
        return putModelWithResponseAsync(fish).flatMap(res -> Mono.justOrEmpty(res.getValue()));
    }

    /**
     * The putModel operation.
     * 
     * @param fish The fish parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic multiple levels inheritance with a discriminator.
     */
    public Response<FishInner> putModelWithResponse(FishInner fish) {
        return putModelWithResponseAsync(fish).block();
    }

    /**
     * The putModel operation.
     * 
     * @param fish The fish parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic multiple levels inheritance with a discriminator.
     */
    public FishInner putModel(FishInner fish) {
        return putModelWithResponse(fish, Context.none()).getValue();
    }

    /**
     * The getOutputOnlyModel operation.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic OutputOnlyModel on successful completion of {@link Mono}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private Mono<Response<OutputOnlyModelInner>> getOutputOnlyModelWithResponseAsync() {
        if (this.client.getEndpoint() == null) {
            return Mono.error(
                new IllegalArgumentException("Parameter this.client.getEndpoint() is required and cannot be null."));
        }
        final String accept = "application/json";
        return FluxUtil.withContext(context -> service.getOutputOnlyModel(this.client.getEndpoint(), accept))
            .contextWrite(context -> context.putAll(FluxUtil.toReactorContext(this.client.getContext()).readOnly()));
    }

    /**
     * The getOutputOnlyModel operation.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic OutputOnlyModel on successful completion of {@link Mono}.
     */
    private Mono<OutputOnlyModelInner> getOutputOnlyModelAsync() {
        return getOutputOnlyModelWithResponseAsync().flatMap(res -> Mono.justOrEmpty(res.getValue()));
    }

    /**
     * The getOutputOnlyModel operation.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic OutputOnlyModel.
     */
    public Response<OutputOnlyModelInner> getOutputOnlyModelWithResponse() {
        return getOutputOnlyModelWithResponseAsync().block();
    }

    /**
     * The getOutputOnlyModel operation.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic OutputOnlyModel.
     */
    public OutputOnlyModelInner getOutputOnlyModel() {
        return getOutputOnlyModelWithResponse(Context.none()).getValue();
    }
}
