// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package tsptest.armstreamstyleserialization.implementation;

import com.azure.v2.core.util.FluxUtil;
import io.clientcore.core.annotations.ReturnType;
import io.clientcore.core.annotations.ServiceInterface;
import io.clientcore.core.annotations.ServiceMethod;
import io.clientcore.core.http.RestProxy;
import io.clientcore.core.http.annotations.BodyParam;
import io.clientcore.core.http.annotations.HeaderParam;
import io.clientcore.core.http.annotations.HostParam;
import io.clientcore.core.http.annotations.HttpRequestInformation;
import io.clientcore.core.http.annotations.UnexpectedResponseExceptionDetail;
import io.clientcore.core.http.exceptions.HttpResponseException;
import io.clientcore.core.http.models.HttpMethod;
import io.clientcore.core.http.models.Response;
import io.clientcore.core.http.pipeline.HttpPipeline;
import io.clientcore.core.serialization.ObjectSerializer;
import io.clientcore.core.utils.Context;
import java.lang.reflect.InvocationTargetException;
import reactor.core.publisher.Mono;
import tsptest.armstreamstyleserialization.fluent.FunctionsClient;
import tsptest.armstreamstyleserialization.fluent.models.FunctionInner;

/**
 * An instance of this class provides access to all the operations defined in FunctionsClient.
 */
public final class FunctionsClientImpl implements FunctionsClient {
    /**
     * The proxy service used to perform REST calls.
     */
    private final FunctionsService service;

    /**
     * The service client containing this operation class.
     */
    private final ArmStreamStyleSerializationClientImpl client;

    /**
     * Initializes an instance of FunctionsClientImpl.
     * 
     * @param client the instance of the service client containing this operation class.
     */
    FunctionsClientImpl(ArmStreamStyleSerializationClientImpl client) {
        this.service = RestProxy.create(FunctionsService.class, client.getHttpPipeline());
        this.client = client;
    }

    /**
     * The interface defining all the services for ArmStreamStyleSerializationClientFunctions to be used by the proxy
     * service to perform REST calls.
     */
    @ServiceInterface(name = "ArmStreamStyleSerial", host = "{endpoint}")
    public interface FunctionsService {
        static FunctionsService getNewInstance(HttpPipeline pipeline, ObjectSerializer serializer) {
            try {
                Class<?> clazz
                    = Class.forName("tsptest.armstreamstyleserialization.implementation.FunctionsServiceImpl");
                return (FunctionsService) clazz.getMethod("getNewInstance", HttpPipeline.class, ObjectSerializer.class)
                    .invoke(null, pipeline, serializer);
            } catch (ClassNotFoundException | NoSuchMethodException | IllegalAccessException
                | InvocationTargetException e) {
                throw new RuntimeException(e);
            }

        }

        @HttpRequestInformation(method = HttpMethod.PUT, path = "/function", expectedStatusCodes = { 200 })
        @UnexpectedResponseExceptionDetail
        Mono<Response<FunctionInner>> createFunction(@HostParam("endpoint") String endpoint,
            @HeaderParam("Content-Type") String contentType, @HeaderParam("Accept") String accept,
            @BodyParam("application/json") FunctionInner function);
    }

    /**
     * The createFunction operation.
     * 
     * @param function The function parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response body on successful completion of {@link Mono}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private Mono<Response<FunctionInner>> createFunctionWithResponseAsync(FunctionInner function) {
        if (this.client.getEndpoint() == null) {
            return Mono.error(
                new IllegalArgumentException("Parameter this.client.getEndpoint() is required and cannot be null."));
        }
        if (function == null) {
            return Mono.error(new IllegalArgumentException("Parameter function is required and cannot be null."));
        } else {
            function.validate();
        }
        final String contentType = "application/json";
        final String accept = "application/json";
        return FluxUtil
            .withContext(context -> service.createFunction(this.client.getEndpoint(), contentType, accept, function))
            .contextWrite(context -> context.putAll(FluxUtil.toReactorContext(this.client.getContext()).readOnly()));
    }

    /**
     * The createFunction operation.
     * 
     * @param function The function parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response body on successful completion of {@link Mono}.
     */
    private Mono<FunctionInner> createFunctionAsync(FunctionInner function) {
        return createFunctionWithResponseAsync(function).flatMap(res -> Mono.justOrEmpty(res.getValue()));
    }

    /**
     * The createFunction operation.
     * 
     * @param function The function parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    public Response<FunctionInner> createFunctionWithResponse(FunctionInner function) {
        return createFunctionWithResponseAsync(function).block();
    }

    /**
     * The createFunction operation.
     * 
     * @param function The function parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    public FunctionInner createFunction(FunctionInner function) {
        return createFunctionWithResponse(function, Context.none()).getValue();
    }
}
