// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package tsptest.armstreamstyleserialization.models;

import io.clientcore.core.http.models.Response;
import tsptest.armstreamstyleserialization.fluent.models.FunctionInner;

/**
 * Resource collection API of Functions.
 */
public interface Functions {
    /**
     * The createFunction operation.
     * 
     * @param function The function parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    Response<Function> createFunctionWithResponse(FunctionInner function);

    /**
     * The createFunction operation.
     * 
     * @param function The function parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    Function createFunction(FunctionInner function);
}
