// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package tsptest.armstreamstyleserialization.fluent;

import io.clientcore.core.http.exceptions.HttpResponseException;
import io.clientcore.core.http.models.Response;
import tsptest.armstreamstyleserialization.fluent.models.FishInner;
import tsptest.armstreamstyleserialization.fluent.models.OutputOnlyModelInner;

/**
 * An instance of this class provides access to all the operations defined in FishesClient.
 */
public interface FishesClient {
    /**
     * The getModel operation.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic multiple levels inheritance with a discriminator.
     */
    Response<FishInner> getModelWithResponse();

    /**
     * The getModel operation.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic multiple levels inheritance with a discriminator.
     */
    FishInner getModel();

    /**
     * The putModel operation.
     * 
     * @param fish The fish parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic multiple levels inheritance with a discriminator.
     */
    Response<FishInner> putModelWithResponse(FishInner fish);

    /**
     * The putModel operation.
     * 
     * @param fish The fish parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic multiple levels inheritance with a discriminator.
     */
    FishInner putModel(FishInner fish);

    /**
     * The getOutputOnlyModel operation.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic OutputOnlyModel.
     */
    Response<OutputOnlyModelInner> getOutputOnlyModelWithResponse();

    /**
     * The getOutputOnlyModel operation.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return this is base model for polymorphic OutputOnlyModel.
     */
    OutputOnlyModelInner getOutputOnlyModel();
}
